{TSLOIM_data_path_GF2: 'C:\Users\david.mercier\Documents\GitHub\stabix\A_gui_plotmap\ebsd_dataExamples',
  TSLOIM_data_path_RB: 'C:\Users\david.mercier\Documents\GitHub\stabix\A_gui_plotmap\ebsd_dataExamples'}
