# YAML configuration file to set crystal plasticity finite element modelling
# Authors : D. Mercier and C. Zambaldi
# Give only absolute paths and put a space after the comma in a list (e.g. [x, y, z]) !!!
# Don't modify fieldnames !

# the CPFEM code that you want to use, e.g. GENMAT or DAMASK
simulation_code: GENMAT
#simulation_code: DAMASK

# list of FEM solvers
fem_solvers:
    - Mentat_2014-2017
    - Mentat_2013.1
    - Mentat_2013
    - Mentat_2012
    - Mentat_2010
    - Mentat_2008
    - Abaqus_2014
    - Abaqus_2012

# the FEM solvers that you want to use, e.g. Mentat2012 or Mentat2013
fem_solver_used: Mentat_2013.1

# list of Python executables (e.g.: 'C:\Python27\python.exe')
python_executables:
    - 'C:\Python27\python.exe'
    - 'C:\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\python3.exe'

# where you want the Mentat or Abaqus procedure file written
#proc_file_path: /Users/<username>/Documents/mwn2/matlab #for MAC
proc_file_path: \\mufs4\home\<username> # for PC
